os:
  - linux
language: perl6
perl6:
  - latest
install:
  - rakudobrew build-zef
  - zef --debug --depsonly --test-depends --/test install .
script:
  - PERL6LIB=$PWD/lib zef build .
  - PERL6LIB=$PWD/lib prove -e perl6 -vr t/
sudo: false
